---

- name: Converge Zookeeper
  hosts: zookeeper
  tasks:
    - name: "Include java role for zookeeper"
      include_role:
        name: "java"

    - name: "Include ansible-role-zookeeper"
      include_role:
        name: "zookeeper"
      vars:
        zookeeper_servers: "{{ groups['zookeeper'] }}"
        # assuming zookeeper regex hostname is 'zookeeper\d{2}'
        zookeeper_id: "{{ ansible_hostname | regex_search('^zookeeper(\\d{2})', '\\1') | first }}"

- name: Converge Clickhouse
  hosts: clickhouse
  tasks:
    - name: "Include ansible-role-clickhouse"
      include_role:
        name: "ansible-role-clickhouse"
      vars:
        # override: set as 0.0.0.0 because clickhouse_replica_name is an alias of 127.0.0.1 in /etc/hosts due to libnss-mdns
        # important: no set 0.0.0.0 in real world envs
        clickhouse_listen_host_default:
          - "::1"
          - "0.0.0.0"
