---

- name: Converge Zookeeper
  hosts: zookeeper
  tasks:
    - name: "Include java role for zookeeper"
      include_role:
        name: "java"

    - name: "Include ansible-role-zookeeper"
      include_role:
        name: "zookeeper"

- name: Converge Clickhouse
  hosts: clickhouse
  tasks:
    - name: "Include ansible-role-clickhouse"
      include_role:
        name: "ansible-role-clickhouse"
      vars:
        # override because  clickhouse_replica_name is an alias of 127.0.0.1 because virtual box and libnss-mdns
        clickhouse_listen_host_default:
          - "{{ clickhouse_replica_name }}"
          - "::1"
