---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: molecule/default/requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: zookeeper01.local
    box: ubuntu/bionic64
    memory: 2048
    cpus: 1
    hostname: zookeeper01.local
    interfaces:
      - network_name: private_network
        ip: 192.168.69.60
        virtualbox__intnet: true
    groups:
      - zookeeper
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
  - name: ch-shard01-replica01.local
    box: centos/7
    memory: 2048
    cpus: 1
    hostname: ch-shard01-replica01.local
    interfaces:
      - network_name: private_network
        ip: 192.168.69.69
        virtualbox__intnet: true
    groups:
      - clickhouse
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
  - name: ch-shard01-replica02.local
    box: centos/7
    memory: 2048
    cpus: 1
    hostname: ch-shard01-replica02.local
    interfaces:
      - network_name: private_network
        ip: 192.168.69.70
        virtualbox__intnet: true
    groups:
      - clickhouse
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
  # - name: ch-shard02-replica01.local
  #   box: centos/7
  #   memory: 2048
  #   cpus: 1
  #   hostname: ch-shard02-replica01.local
  #   interfaces:
  #     - network_name: private_network
  #       ip: 192.168.69.72
  #       virtualbox__intnet: true
  #   groups:
  #     - clickhouse
  #   config_options:
  #     ssh.keep_alive: yes
  #     ssh.remote_user: "'vagrant'"
  # - name: ch-shard02-replica02.local
  #   box: centos/7
  #   memory: 2048
  #   cpus: 1
  #   hostname: ch-shard02-replica02.local
  #   interfaces:
  #     - network_name: private_network
  #       ip: 192.168.69.73
  #       virtualbox__intnet: true
  #   groups:
  #     - clickhouse
  #   config_options:
  #     ssh.keep_alive: yes
  #     ssh.remote_user: "'vagrant'"
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
lint: |
  set -e
  yamllint .
  ansible-lint
# verifier:
#   name: testinfra
#   options:
#     sudo: true
#     v: 1