---
- name: Prepare
  hosts: all
  tasks:
    - name: Install epel-release RHEL
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

    - name: Install nss-mdns RHEL
      yum:
        name: ['nss-mdns', 'net-tools', 'nc']
        state: present
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

    - name: Install libnss-mdns Install Debian
      apt:
        name: libnss-mdns
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Restart avahi-daemon
      service:
        name: avahi-daemon
        state: restarted
